# Site settings
title: Title is here
author: Rhythmszk the author
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  "this is a description, quotation mark"
# show_excerpts: true
# markdown: kramdown


# Build settings
theme: minima
minima:
  skin: dark
# remote_theme: jekyll/minima # Alternative way
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext


header_pages:
- README.md
- about.md
- 2021-06-29-languages.md

# Ignore stuff
# exclude:
# - README.md
 

